# -*- coding: utf-8 -*-
"""Phylogenetic analysis on DNA Sequences

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5GTp-zhfQM7SKzP3QvEO8zf-mrK3CXI
"""

!pip install biopython

import Bio as Bio

from Bio import SeqIO
from Bio import AlignIO
from Bio import Phylo

t1 = SeqIO.read("/content/BonyFish.txt", "fasta")
t2 = SeqIO.read("/content/HomoSapien.txt", "fasta")
t3 = SeqIO.read("/content/MusMusculus.txt", "fasta")

APOEspecies = SeqIO.write([t1,t2,t3],"/content/APOEspec","fasta")

with open("/content/alignedAPOE.aln-clustalw","r") as aln:
  alignment = AlignIO.read(aln,"clustal")
print(type(alignment))

from Bio.Phylo.TreeConstruction import DistanceCalculator
calculator = DistanceCalculator('identity')

distance_matrix = calculaator.get_distance(alignment)
print(distance_matrix)

from Bio.Phylo.TreeConstruction import DistanceTreeConstructor
constructor = DistanceTreeConstructor(calculator)

APOE_tree = constructor.build_tree(alignment)
APOE_tree.rooter = True
print(APOE_tree)

Phylo.write(APOE_tree,"/content/APOEtree.txt","phyloxml")

import matplotlib
import matplotlib.pyplot as plt
fig = Phylo.draw(APOE_tree)